.\a_atack1.nam.saanim
.\a_atack2.nam.saanim
.\a_atack3.nam.saanim
.\a_atack4.nam.saanim
.\a_baneup0.nam.saanim
.\a_baneup1.nam.saanim
.\a_baneup2.nam.saanim
.\a_chissoku0.nam.saanim
.\a_dorumon0.nam.saanim
.\a_dorumon1.nam.saanim
.\a_dwalk0.nam.saanim
.\a_eggshake0.nam.saanim
.\a_eggshake1.nam.saanim
.\a_eggshake2.nam.saanim
.\a_h_baneup0.nam.saanim
.\a_h_baneup1.nam.saanim
.\a_h_baneup2.nam.saanim
.\a_h_baneup3.nam.saanim
.\a_h_run0.nam.saanim
.\a_h_wait0.nam.saanim
.\a_h_walk0.nam.saanim
.\a_hashigo0.nam.saanim
.\a_hold0.nam.saanim
.\a_holdstop0.nam.saanim
.\a_holdstop1.nam.saanim
.\a_jumpat0.nam.saanim
.\a_kaitenkey0.nam.saanim
.\a_kaitenkey1.nam.saanim
.\a_kakure0.nam.saanim
.\a_kimepose0.nam.saanim
.\a_taiki0.nam.saanim
.\a_taiki1.nam.saanim
.\a_taiki2.nam.saanim
.\a_n_damage0.nam.saanim
.\a_n_damage1.nam.saanim
.\a_n_die0.nam.saanim
.\a_n_die1.nam.saanim
.\a_push0.nam.saanim
.\a_rocket0.nam.saanim
.\a_rocket1.nam.saanim
.\a_rollat0.nam.saanim
.\a_rollat1.nam.saanim
.\a_rollat2.nam.saanim
.\a_rollat3.nam.saanim
.\a_run0.nam.saanim
.\a_run1.nam.saanim
.\a_run2.nam.saanim
.\a_runat0.nam.saanim
.\a_runat1.nam.saanim
.\a_runat2.nam.saanim
.\a_runat4.nam.saanim
.\a_runat5.nam.saanim
.\a_runat6.nam.saanim
.\a_sakataiki0.nam.saanim
.\a_sakataiki1.nam.saanim
.\a_shake0.nam.saanim
.\a_stop0.nam.saanim
.\a_stop1.nam.saanim
.\a_mogura0.nam.saanim
.\a_mogura1.nam.saanim
.\a_mogura2.nam.saanim
.\a_takeback0.nam.saanim
.\a_throw0.nam.saanim
.\a_throw1.nam.saanim
.\a_touch0.nam.saanim
.\a_touch1.nam.saanim
.\a_tukamari0.nam.saanim
.\a_wait_a0.nam.saanim
.\a_wait_a1.nam.saanim
.\a_wait0.nam.saanim
.\a_walk0.nam.saanim
.\a_zitabata.nam.saanim
.\a_zou0.nam.saanim
.\a_zou1.nam.saanim
.\a_chaonade0.nam.saanim
.\a_chaonade1.nam.saanim
.\a_chaonade2.nam.saanim
.\a_kutibue.nam.saanim
