.\k_anahori0.nam.saanim
.\k_anahori1.nam.saanim
.\k_baneup2.nam.saanim
.\k_chissoku0.nam.saanim
.\k_crash0.nam.saanim
.\k_crash1.nam.saanim
.\k_eggshake0.nam.saanim
.\k_eggshake1.nam.saanim
.\k_eggshake2.nam.saanim
.\k_h_run0.nam.saanim
.\k_h_stop0.nam.saanim
.\k_h_stop1.nam.saanim
.\k_h_wait0.nam.saanim
.\k_h_walk0.nam.saanim
.\k_hashigo.nam.saanim
.\k_hold0.nam.saanim
.\k_item_c0.nam.saanim
.\k_item_c1.nam.saanim
.\k_item_c2.nam.saanim
.\k_item_fg0.nam.saanim
.\k_item_fg1.nam.saanim
.\k_item_fg2.nam.saanim
.\k_kabeup0.nam.saanim
.\k_kimepose0.nam.saanim
.\k_kimepose1.nam.saanim
.\k_n_damage0.nam.saanim
.\k_n_damage1.nam.saanim
.\k_n_die0.nam.saanim
.\k_n_die1.nam.saanim
.\k_panch0.nam.saanim
.\k_panch1.nam.saanim
.\k_panch2.nam.saanim
.\k_panch22.nam.saanim
.\k_push1.nam.saanim
.\k_rocket0.nam.saanim
.\k_rocket1.nam.saanim
.\k_rollfly0.nam.saanim
.\k_run0.nam.saanim
.\k_sakataiki0.nam.saanim
.\k_sakataiki1.nam.saanim
.\k_shake0.nam.saanim
.\k_standup1.nam.saanim
.\k_stop0.nam.saanim
.\k_stop1.nam.saanim
.\k_taiki0.nam.saanim
.\k_taiki1.nam.saanim
.\k_taiki2.nam.saanim
.\k_takeback0.nam.saanim
.\k_throw0.nam.saanim
.\k_throw1.nam.saanim
.\k_touch0.nam.saanim
.\k_touch1.nam.saanim
.\k_tukamari0.nam.saanim
.\k_u_taiki0.nam.saanim
.\k_u_taiki1.nam.saanim
.\k_untei1.nam.saanim
.\k_wait_a0.nam.saanim
.\k_wait_a1.nam.saanim
.\k_wait_b0.nam.saanim
.\k_wait_b1.nam.saanim
.\k_wait0.nam.saanim
.\k_walk0.nam.saanim
.\k_walk1.nam.saanim
.\k_chaonade0.nam.saanim
.\k_chaonade1.nam.saanim
.\k_chaonade2.nam.saanim
.\k_kutibue.nam.saanim
