.\k_anaup0.nam.saanim
.\k_anaup1.nam.saanim
.\k_baneup0.nam.saanim
.\k_baneup1.nam.saanim
.\k_baneup3.nam.saanim
.\k_fly0.nam.saanim
.\k_fly1.nam.saanim
.\k_fly2.nam.saanim
.\k_h_baneup0.nam.saanim
.\k_h_baneup1.nam.saanim
.\k_h_baneup2.nam.saanim
.\k_h_baneup3.nam.saanim
.\k_kabe0.nam.saanim
.\k_kabe1.nam.saanim
.\k_kabe2.nam.saanim
.\k_kabewait0.nam.saanim
.\k_lkabe0.nam.saanim
.\k_rkabe0.nam.saanim
.\k_run1.nam.saanim
.\k_zitabata.nam.saanim
