.\action_e101r_deffence_l.nam.saanim
.\action_e101r_deffence_r.nam.saanim
.\action_e101r_return.nam.saanim
.\action_e101r_damage.nam.saanim
.\action_e101r_damage2.nam.saanim
.\action_e101r_wait.nam.saanim
.\action_e101r_hadou.nam.saanim
.\action_e101r_attack.nam.saanim
.\action_e101r_dead.nam.saanim
