.\e_wait0.nam.saanim
.\e_wait1.nam.saanim
.\e_wait2.nam.saanim
.\e_walk0.nam.saanim
.\e_run0.nam.saanim
.\e_run1.nam.saanim
.\e_run2.nam.saanim
.\e_jump00.nam.saanim
.\e_jump0.nam.saanim
.\e_jump1.nam.saanim
.\e_jump2.nam.saanim
.\e_jump3.nam.saanim
.\e_stop0.nam.saanim
.\e_stop1.nam.saanim
.\e_stop4.nam.saanim
.\e_wchange0.nam.saanim
.\e_wchange1.nam.saanim
.\e_crash0.nam.saanim
.\e_wwait0.nam.saanim
.\e_touch0.nam.saanim
.\e_shake0.nam.saanim
.\e_push0.nam.saanim
.\e_push1.nam.saanim
.\e_takeback.nam.saanim
.\e_hjump00.nam.saanim
.\e_hjump0.nam.saanim
.\e_hjump1.nam.saanim
.\e_hjump2.nam.saanim
.\e_hjump3.nam.saanim
.\e_hwchange0.nam.saanim
.\e_hwchange1.nam.saanim
.\e_hwwait0.nam.saanim
.\e_hold0.nam.saanim
.\e_hwalk0.nam.saanim
.\e_hrun0.nam.saanim
.\e_hrun1.nam.saanim
.\e_hrun2.nam.saanim
.\e_hstop0.nam.saanim
.\e_hstop1.nam.saanim
.\e_hwait0.nam.saanim
.\e_throw0.nam.saanim
.\e_throw1.nam.saanim
.\e_hover0.nam.saanim
.\e_hover1.nam.saanim
.\e_shoot0.nam.saanim
.\e_shoot1.nam.saanim
.\e_hashigo0.nam.saanim
.\e_kimepose0.nam.saanim
.\e_kimepose1.nam.saanim
.\e_die.nam.saanim
.\e_n_damage0.nam.saanim
.\e_n_damage1.nam.saanim
.\e_wait_a0.nam.saanim
.\e_wait_a1.nam.saanim
.\e_chaonade0.nam.saanim
.\e_chaonade1.nam.saanim
.\e_chaonade2.nam.saanim
.\e_kutibue.nam.saanim
.\e_item_f0.nam.saanim
.\e_item_f1.nam.saanim
.\e_item_f2.nam.saanim
.\e_item_g0.nam.saanim
.\e_item_g1.nam.saanim
.\e_item_g2.nam.saanim
.\e_eggshake0.nam.saanim
.\e_eggshake1.nam.saanim
.\e_eggshake2.nam.saanim
.\e_sakataiki0.nam.saanim
.\e_sakataiki1.nam.saanim
.\e_taiki0.nam.saanim
