.\b_atcast0.nam.saanim
.\b_baneup0.nam.saanim
.\b_baneup1.nam.saanim
.\b_cast00.nam.saanim
.\b_h_baneup0.nam.saanim
.\b_h_baneup1.nam.saanim
.\b_h_jump0.nam.saanim
.\b_h_jump1.nam.saanim
.\b_mh_run0.nam.saanim
.\b_mh_wait0.nam.saanim
.\b_mh_walk0.nam.saanim
.\b_mhold0.nam.saanim
.\b_jump0.nam.saanim
.\b_jump1.nam.saanim
.\b_push0.nam.saanim
.\b_run0.nam.saanim
.\b_shake0.nam.saanim
.\b_takeback0.nam.saanim
.\b_throw0.nam.saanim
.\b_throw1.nam.saanim
.\b_touch0.nam.saanim
.\b_touch1.nam.saanim
.\b_wait0.nam.saanim
.\b_walk0.nam.saanim
.\b_hashigo0.nam.saanim
.\b_kimepose0.nam.saanim
.\b_zitabata0.nam.saanim
.\b_cast01.nam.saanim
.\b_cast1.nam.saanim
.\b_cast2.nam.saanim
.\b_cast3.nam.saanim
.\b_cast4.nam.saanim
.\b_cast5.nam.saanim
.\b_cast6.nam.saanim
.\b_joysmall.nam.saanim
.\b_joymiddle.nam.saanim
.\b_joybig0.nam.saanim
.\b_wcast2.nam.saanim
.\b_wcast3.nam.saanim
.\b_wcast4.nam.saanim
.\b_wcast5.nam.saanim
.\b_wcast6.nam.saanim
.\b_h_wait0.nam.saanim
.\b_h_walk0.nam.saanim
.\b_h_run0.nam.saanim
.\b_hold0.nam.saanim
.\b_wcast0.nam.saanim
.\b_wcast1.nam.saanim
.\b_miss0.nam.saanim
.\b_miss1.nam.saanim
.\b_miss2.nam.saanim
.\b_n_damage0.nam.saanim
.\b_n_damage1.nam.saanim
.\b_n_die0.nam.saanim
.\b_awa0.nam.saanim
.\b_wswim0.nam.saanim
.\b_wdown0.nam.saanim
.\b_wdown1.nam.saanim
.\b_wswim1.nam.saanim
.\b_wup0.nam.saanim
.\b_wup1.nam.saanim
.\b_wwait0.nam.saanim
.\b_wait_a0.nam.saanim
.\b_wait_a1.nam.saanim
.\b_eggshake0.nam.saanim
.\b_eggshake1.nam.saanim
.\b_eggshake2.nam.saanim
.\b_chissoku0.nam.saanim
.\b_taiki0.nam.saanim
.\b_taiki1.nam.saanim
.\b_taiki2.nam.saanim
.\b_sakataiki0.nam.saanim
.\b_sakataiki1.nam.saanim
.\b_chaonade0.nam.saanim
.\b_chaonade1.nam.saanim
.\b_chaonade2.nam.saanim
.\b_kutibue.nam.saanim
