.\c0_atack0.nam.saanim
.\c0_atack1.nam.saanim
.\c0_atack2.nam.saanim
.\c0_damege0.nam.saanim
.\c0_guard0.nam.saanim
.\c0_guard1.nam.saanim
.\c0_jump0.nam.saanim
.\c0_jump1.nam.saanim
.\c0_jump2.nam.saanim
.\c0_jump3.nam.saanim
.\c0_pdamage0.nam.saanim
.\c0_pdamage1.nam.saanim
.\c0_pjump3.nam.saanim
.\c0_pwait0.nam.saanim
.\c0_rollat0.nam.saanim
.\c0_wait0.nam.saanim
.\c0_walk0.nam.saanim
