.\action_robo_rock_on.nam.saanim
.\action_robo_punch1.nam.saanim
.\action_robo_punch2.nam.saanim
.\action_robo_punch3.nam.saanim
.\action_robo_punch_tunagi.nam.saanim
.\action_robo_punch_modori.nam.saanim
.\action_robo_f_damage1.nam.saanim
.\action_robo_f_damage2.nam.saanim
.\action_robo_b_damage1.nam.saanim
.\action_robo_b_damage2.nam.saanim
.\action_robo_discover.nam.saanim
.\action_robo_shindou1.nam.saanim
.\action_robo_shindou2.nam.saanim
.\action_robo_move.nam.saanim
.\action_robo_stop.nam.saanim
.\action_robo_rotate.nam.saanim
