.\metalsonic\ms_move2.nam.saanim
.\s_wait0.nam.saanim
.\s_wait3.nam.saanim
.\s_walk0.nam.saanim
.\s_run0.nam.saanim
.\s_run1.nam.saanim
.\s_run2.nam.saanim
.\s_stop0.nam.saanim
.\s_baneup0.nam.saanim
.\s_baneup1.nam.saanim
.\s_baneup2.nam.saanim
.\s_baneup3.nam.saanim
.\s_push1.nam.saanim
.\s_push2.nam.saanim
.\s_rollfly.nam.saanim
.\s_crash0.nam.saanim
.\s_standup0.nam.saanim
.\s_maxrun.nam.saanim
.\s_icemove0.nam.saanim
.\s_stop1.nam.saanim
.\s_standup1.nam.saanim
.\s_hold0.nam.saanim
.\s_holdup0.nam.saanim
.\s_holdup1.nam.saanim
.\s_holdup2.nam.saanim
.\s_holdup3.nam.saanim
.\s_holdrun0.nam.saanim
.\s_holdstop0.nam.saanim
.\s_holdstop1.nam.saanim
.\s_hwait0.nam.saanim
.\s_holdwalk0.nam.saanim
.\s_shake0.nam.saanim
.\s_takeback0.nam.saanim
.\s_throw0.nam.saanim
.\s_throw1.nam.saanim
.\s_throwup0.nam.saanim
.\s_throwup1.nam.saanim
.\s_touch0.nam.saanim
.\s_touch1.nam.saanim
.\s_tranpo0.nam.saanim
.\s_tranpo1.nam.saanim
.\s_tranpo2.nam.saanim
.\s_tranpo3.nam.saanim
.\s_carton.nam.saanim
.\s_tumazuki.nam.saanim
.\s_tukamari0.nam.saanim
.\s_untei1.nam.saanim
.\s_u_taiki0.nam.saanim
.\s_u_taiki1.nam.saanim
.\s_sbright0.nam.saanim
.\s_sbleft0.nam.saanim
.\s_sbldamege0.nam.saanim
.\s_sbrdamege0.nam.saanim
.\s_sblstop0.nam.saanim
.\s_sbrstop0.nam.saanim
.\s_sbjump0.nam.saanim
.\s_sbjump1.nam.saanim
.\s_sbfront0.nam.saanim
.\s_sbfront1.nam.saanim
.\s_sbdown0.nam.saanim
.\s_sbdown1.nam.saanim
.\s_sbdown2.nam.saanim
.\s_sbwait0.nam.saanim
.\s_sbwait1.nam.saanim
.\s_sbsa0.nam.saanim
.\s_sbsa1.nam.saanim
.\s_sbsa2.nam.saanim
.\s_sbsb0.nam.saanim
.\s_turajump0.nam.saanim
.\s_turajump1.nam.saanim
.\s_turalrot.nam.saanim
.\s_turarrot.nam.saanim
.\s_turawait0.nam.saanim
.\s_turawait1.nam.saanim
.\s_hasigo0.nam.saanim
.\s_zitabata.nam.saanim
.\s_suberi0.nam.saanim
.\s_sakataiki0.nam.saanim
.\s_sakataiki1.nam.saanim
.\s_rocket0.nam.saanim
.\s_rocket1.nam.saanim
.\s_kimepose0.nam.saanim
.\s_kimepose1.nam.saanim
.\s_slider0.nam.saanim
.\s_furatsuki0.nam.saanim
.\s_hmove0.nam.saanim
.\s_hmove1.nam.saanim
.\s_holdwait0.nam.saanim
.\s_sbss0.nam.saanim
.\s_sbss1.nam.saanim
.\s_sbss2.nam.saanim
.\s_pjump0.nam.saanim
.\s_pjump1.nam.saanim
.\s_awa0.nam.saanim
.\s_n_damage0.nam.saanim
.\s_n_damage1.nam.saanim
.\s_die0.nam.saanim
.\s_lspind0.nam.saanim
.\s_wait_a0.nam.saanim
.\s_wait_a1.nam.saanim
.\s_wait_b0.nam.saanim
.\s_wait_b1.nam.saanim
.\s_eggshake0.nam.saanim
.\s_eggshake1.nam.saanim
.\s_eggshake2.nam.saanim
.\s_chissoku0.nam.saanim
.\s_h_zuriochi0.nam.saanim
.\s_h_zuriochi1.nam.saanim
.\s_dorootoshi0.nam.saanim
.\s_sowewr0.nam.saanim
.\s_sowewr1.nam.saanim
.\s_sowewr2.nam.saanim
.\s_chaonade0.nam.saanim
.\s_chaonade1.nam.saanim
.\s_chaonade2.nam.saanim
.\s_kutibue.nam.saanim
