.\sb_sbright0.nam.saanim
.\sb_sbleft0.nam.saanim
.\sb_sbldamege0.nam.saanim
.\sb_sbrdamege0.nam.saanim
.\sb_sblstop0.nam.saanim
.\sb_sbrstop0.nam.saanim
.\sb_sbdown0.nam.saanim
.\sb_sbjump0.nam.saanim
.\sb_sbjump1.nam.saanim
.\sb_sbdown1.nam.saanim
.\sb_sbsa0.nam.saanim
.\sb_sbsa1.nam.saanim
.\sb_sbsa2.nam.saanim
.\sb_sbsb0.nam.saanim
.\sb_sbss0.nam.saanim
.\sb_sbss1.nam.saanim
.\sb_sbss2.nam.saanim
