.\ss_wait0.nam.saanim
.\ss_move0.nam.saanim
.\ss_move1.nam.saanim
.\ss_move2.nam.saanim
.\ss_baneup0.nam.saanim
.\ss_baneup1.nam.saanim
.\ss_baneup2.nam.saanim
.\ss_baneup3.nam.saanim
.\ss_kimepose0.nam.saanim
.\ss_kimepose1.nam.saanim
