.\m_atack_1.nam.saanim
.\m_atack_2.nam.saanim
.\m_atack_3.nam.saanim
.\m_atack_4.nam.saanim
.\m_atack_5.nam.saanim
.\m_atack_6.nam.saanim
.\m_atack_7.nam.saanim
.\m_atack_8.nam.saanim
.\m_atack_9.nam.saanim
.\m_atack_10.nam.saanim
.\m_atack_11.nam.saanim
.\m_flyup.nam.saanim
.\m_fly0.nam.saanim
.\m_fly1.nam.saanim
.\m_fly2.nam.saanim
.\m_sbjump0.nam.saanim
.\m_sbjump1.nam.saanim
