.\mb_sbjump0.nam.saanim
.\mb_sbjump1.nam.saanim
.\mb_sbdown1.nam.saanim
.\mb_sbleft0.nam.saanim
.\mb_sbldamage.nam.saanim
.\mb_sbrdamage.nam.saanim
.\mb_sbright0.nam.saanim
.\mb_sbsb0.nam.saanim
.\mb_sbss0.nam.saanim
.\mb_sbss1.nam.saanim
