c2_wait0.nam.saanim
c2_walk0.nam.saanim
c2_r_punch.nam.saanim
c2_p_suki.nam.saanim
c2_l_punch.nam.saanim
c2_jump0.nam.saanim
c2_jump1.nam.saanim
c2_h_punch0.nam.saanim
c2_h_punch1.nam.saanim
c2_h_punch2.nam.saanim
c2_guard0.nam.saanim
c2_guard1.nam.saanim
